# Generated by Django 5.0.6 on 2025-02-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_alter_userprofile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default='unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserProfileExtra',
        ),
    ]
