# Generated by Django 5.0.6 on 2025-02-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_userprofile_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='resume',
            field=models.URLField(blank=True, null=True),
        ),
    ]
